spring:
  application:
    name: service-provider
  main:
    allow-bean-definition-overriding: true
server:
  port: 9999

dubbo:
  scan:
    base-packages: net.gzspark.service.impl
  protocol:
    id: dubbo
    name: dubbo
    port: 20882
  registry:
    id: dubboRegistry
    timeout: 5000
    address: zookeeper://192.168.2.173:2181
    client: curator
  metadata-report:
    address: zookeeper://192.168.2.173:2181
logging:
  path: ./logs
